
# ===== Folder Structure =====

INPUT=INPUT/
OUTPUT=OUTPUT/
SUCCESS=SUCCESS/
FAILURE=FAILURE/
AuditLog=Log/


# ===== Validation File =====
# Excel validation file used for mandatory, datatype, length validations.

validationFilePath=RBI Generic Validation.xls


# ===== Output File Naming Convention =====
# Final output format must be:  DOMAINID_CLIENTCODE_CLIENTCODEDDMM.srl
# Example Output: EPILCX_8503RBI_8503RBIDDMM.srl

DomainId = EPILCX
ClientCode = 8503RBI
OutputNamingwithDomainName = Y


# ===== Additional Config =====
RecordLevelRejection = N   # File should not be rejected even if some records fail
TIMER_REQUIRED = N         # Scheduling not required
RUN_TIME_INTERVAL = 1      # Not used when TIMER_REQUIRED = N

InputFileDateFormat = dd/MM/yyyy

FileCounterPath=fileCounter.properties
